---
- name: Fail Cilium CNI Install
  ansible.builtin.fail:
    msg: "Cilium CNI feature is not implemented yet."

- name: Get current Cilium CLI version
  shell: >
    curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
  register: cilium_cli_version

- name: Download Cilium CLI
  shell: >
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz
  
# sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
# rm cilium-linux-amd64.tar.gz{,.sha256sum}
