---
- name: Add HAMi helm chart repo
  shell: >-
    helm --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig repo add hami-charts https://project-hami.github.io/HAMi/

- name: Run helm repo update
  shell: >-
    helm --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig repo update

- name: Install HAMi GPU Operator
  shell: >-
    helm --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig install hami hami-charts/hami -n kube-system
