---
- name: Workload | Create auto-scaler deployment template
  template:
    src: "autoscaler-deployment.yml.j2"
    dest: "{{ tmp_dir }}/autoscaler-deployment.yml"
    mode: 0640

- name: Workload | Deploy auto-scaler for {{ cluster_name }}
  shell: >-
    kubectl apply -f {{ tmp_dir }}/autoscaler-deployment.yml