---
- name: Create high pod priority class template
  template:
    src: "high-prority-class.yml.j2"
    dest: "{{ tmp_dir }}/high-prority-class.yml"
    mode: 0640

- name: Deploy high pod priority class for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/high-prority-class.yml

- name: Create low pod priority class template
  template:
    src: "low-prority-class.yml.j2"
    dest: "{{ tmp_dir }}/low-prority-class.yml"
    mode: 0640

- name: Deploy low pod priority class for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/low-prority-class.yml

- name: Create auto-scaler deployment template
  template:
    src: "autoscaler-deployment.yml.j2"
    dest: "{{ tmp_dir }}/autoscaler-deployment.yml"
    mode: 0640

- name: Deploy auto-scaler for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/autoscaler-deployment.yml

- name: Create dummy pod template
  template:
    src: "dummy-pod.yml.j2"
    dest: "{{ tmp_dir }}/dummy-pod.yml"
    mode: 0640

- name: Deploy dummy pod for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/dummy-pod.yml