---
- name: Get CAPI Managment cluster kubeconfig
  shell: >-
    kubectl get secret {{ capi_management_cluster }}-kubeconfig -o jsonpath='{.data.value}' | base64 --decode >> {{ tmp_dir }}/mgnt-kubeconfig

- name: Set CAPI Managment cluster kubeconfig as secret
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig create secret generic kubeconfig --from-file=kubeconfig={{ tmp_dir }}/mgnt-kubeconfig -n kube-system

- name: Create auto-scaler deployment template
  template:
    src: "autoscaler-deployment.yml.j2"
    dest: "{{ tmp_dir }}/autoscaler-deployment.yml"
    mode: 0640

- name: Deploy auto-scaler for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/autoscaler-deployment.yml

- name: Create high pod priority class template
  template:
    src: "high-priority-class.yml.j2"
    dest: "{{ tmp_dir }}/high-priority-class.yml"
    mode: 0640

- name: Deploy high pod priority class for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/high-priority-class.yml

- name: Create low pod priority class template
  template:
    src: "low-priority-class.yml.j2"
    dest: "{{ tmp_dir }}/low-priority-class.yml"
    mode: 0640

- name: Deploy low pod priority class for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/low-priority-class.yml

- name: Create dummy pod template
  template:
    src: "dummy-pod.yml.j2"
    dest: "{{ tmp_dir }}/dummy-pod.yml"
    mode: 0640

- name: Deploy dummy pod for {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f {{ tmp_dir }}/dummy-pod.yml