---
- name: Install Calico CNI
  include_tasks: cni-calico-install.yml
  when: (cni_provider | default('calico')) == "calico"

- name: Install Calico CNI Operator
  include_tasks: cni-calico-operator-install.yml
  when: (cni_provider | default('calico')) == "calico-operator"

- name: Install Cilium CNI
  include_tasks: cni-cilium-install.yml
  when: (cni_provider | default('calico')) == "cilium"