---
- name: Creating {{ tmp_dir }} if it does not exist
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Ensure clouds.yaml file exists
  stat:
    path: "{{ clouds_yaml_location }}"
  register: clouds_yaml_file
  
- name: Creating {{ kube_config_location }} if it does not exist
  file:
    path: "{{ kube_config_location }}"
    state: directory
    mode: 0755

- name: Ensure kubectl config file exists
  stat:
    path: "{{ kube_config_location }}/config"
  register: kube_config_file

- name: Check kubectl config and clouds.yaml exists
  assert:
    that:
      - clouds_yaml_file.stat.exists
      - kube_config_file.stat.exists

- name: Ensure yq is installed in {{ bin_dir }}
  stat:
    path: "{{ bin_dir }}/yq"
  register: yq_binary

- name: Download yq to specified location {{ bin_dir }}
  get_url:
    url: "{{ yq_repo }}"
    dest: "{{ bin_dir }}/yq"
    mode: 0755
    force: true
  become: true
  when:
    - not yq_binary.stat.exists